# Generated by Django 6.0.4 on 2026-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('profesion', models.CharField(max_length=100, verbose_name='Profesión (Subtítulo Portada)')),
                ('biografia', models.TextField(verbose_name='Biografía Corta')),
                ('biografia_extra', models.TextField(blank=True, null=True, verbose_name='Biografía Extra (Opcional)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='persona', verbose_name='Foto de Perfil (Avatar)')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('descripcion_contacto', models.TextField(verbose_name='Descripción sección Contacto')),
                ('honorarios', models.CharField(blank=True, max_length=100, null=True, verbose_name='Honorarios')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Enlace de GitHub')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Enlace de YouTube')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Enlace de Instagram')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='Enlace de TikTok')),
            ],
            options={
                'verbose_name': 'Datos Personales',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
    ]
